FROM python:3.12.1

ENV PYTHONUNBUFFERED 1

# 作業ディレクトリの作成
RUN mkdir -p /root/workspace
WORKDIR /root/workspace

# パッケージのインストール
COPY requirements.txt /root/workspace/
RUN pip install --upgrade pip \
    && pip install --upgrade setuptools \
    && pip install -r requirements.txt
# アプリケーションコードをコピー
COPY . /root/workspace/

# Djangoサーバーの起動
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
